// <auto-generated />
namespace Feeddit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class userchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202003012042308_userchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
