// <auto-generated />
namespace Feeddit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class cleanup_Vote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cleanup_Vote));
        
        string IMigrationMetadata.Id
        {
            get { return "202003020910410_cleanup_Vote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
