// <auto-generated />
namespace Feeddit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _28022020_AddRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28022020_AddRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202002281632304_28022020_AddRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
